version: '2'

services:
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  web:
    # build:
    #   context: ./
    #   dockerfile: web.dockerfile
    image: nginx:alpine
    working_dir: /var/www/html
    volumes_from:
      - app
    ports:
      - 80:80

  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=blog"
      - "MYSQL_USER=blog"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - 33061:3306

volumes:
  dbdata:
